### ISSUE TITLE
What does number of records mean?

### ISSUE THREAD

**Issue by AugustT** [AugustT/whats_flying_tonight#1]
The number of records feature is really useful. Might it be worthwhile clarifying exactly what this figure is on the about page? I had initially assumed this was the total number of records for the square, rather than just the specific nine-day period. And is it for the user's square or the wider group of nine squares?

**Comment by AugustT** [comment]
I think this is fairly adequately described on the about page, and we don't have the space to elaborate further.

_"The list shows the larger moth species previously recorded in this area (a block of nine 10km x 10km grid squares centred on your location) at around this date (a nine-day period centred on today’s date) and the number of sightings of each."_

**Comment by marcbotham** [comment]
I agree - but could you just add 'over that period' at end or is there literally no space?
